# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "gitREST"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

repositories: 
  adhril : 
    path : /opt/repos/Adhril.com
    name : ''
  crm:
    path : /opt/repos/CRM 
    name : 'crm.server'
    type : 'psgi'
    pidfile : /tmp/crm.pid
    workers : 2
  mki: 
    path : /opt/repos
    name : 'mki.server'
    type : 'fcgi'
  mkie: 
    path : /opt/repos
    name : 'mki.einvoices'
    type : 'fcgi'

gitlog: /tmp/git.log

 


# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

